@startuml blackjack

class ゲーム {
    - ステータス
    + 賭ける(チップ枚数)
    + カードを追加する(手札)
}
class 資金管理 {
    - クレジット
    - 賭けチップ
    + 賭ける(チップ枚数)
    + 配当をもらう(倍率)
    + 賭けチップを没収する()
    + 賭けチップを返す()
}
class 手札 {
    + カードを追加する(追加カード)
    + 得点を計算する()
    + バーストを判定する()
    + ブラックジャック判定する()
}
class 山札 {
    + カードを引く()
}
class カード {
    - 種類
    - マーク
}

ゲーム -- 資金管理
ゲーム -- 手札: プレイヤー手札 >
ゲーム -- 手札: ディーラー手札 >
手札 *-- "2..*" カード 
山札 *-- "0..*" カード
ゲーム -- 山札

@enduml