@startuml blackjack

participant UI
participant ゲーム
participant 山札
participant プレイヤーの手札
participant ディーラーの手札

== ゲーム開始 ==
autonumber 1.1
UI -> ゲーム: ゲームを開始する
ゲーム -> 資金管理: 賭ける
ゲーム -> 山札: カードを引く
ゲーム <-- 山札: カード
ゲーム -> プレイヤーの手札: 手札を作る
ゲーム <-- プレイヤーの手札: 手札
ゲーム -> 山札: カードを引く
ゲーム <-- 山札: カード
ゲーム -> ディーラーの手札: 手札を作る
ゲーム <-- ディーラーの手札: 手札
UI <-- ゲーム: プレイヤーの手札、ディーラーの手札

== プレイヤーのターン ==
autonumber 2.1
loop UIが確定を選択するまで
    alt 確定を選択した場合
        UI -> ゲーム: プレイヤーの手札を確定する
    else カード追加を選択した場合
        UI -> ゲーム: プレイヤーのカードを追加する
        ゲーム -> 山札: カードを引く
        ゲーム <-- 山札: カード
        ゲーム -> プレイヤーの手札: カードを追加する
        ゲーム <-- プレイヤーの手札: 手札
        alt 手札の得点が21点超過の場合
            ゲーム -> 資金管理: 賭けチップを没収する
            ゲーム <-- 資金管理: クレジット
            UI <-- ゲーム: 勝敗結果、クレジット
        else 手札の得点が21点以下の場合
            UI <-- ゲーム: プレイヤーの手札
        end
    end
end

== ディーラーのターン ==
autonumber 3.1
UI -> ゲーム: ディーラーの点数を確定させる
loop ディーラーの点数が17点を超過するまで
    ゲーム -> 山札: カードを引く
    ゲーム <-- 山札: カード
    ゲーム -> ディーラーの手札: カードを追加する
    ゲーム <-- ディーラーの手札: 手札
    alt 手札の得点が21点超過の場合
        ゲーム -> 資金管理: 配当を渡す
        ゲーム <-- 資金管理: 所持チップ枚数
        UI <-- ゲーム: 勝敗結果、所持チップ枚数
    end
end
UI <-- ゲーム: ディーラーの手札

== 勝負 ==
UI -> ゲーム: 勝負する
alt プレイヤーの得点のほうが高い場合
    ゲーム -> 資金管理: 配当をもらう
    ゲーム -> 資金管理: 賭けチップを返す
    ゲーム <-- 資金管理: クレジット
else プレイヤーの得点のほうが低い場合
    ゲーム -> 資金管理: 賭けチップを没収する
    ゲーム <-- 資金管理: クレジット
else プレイヤーとディーラーの得点が同じの場合
    ゲーム -> 資金管理: 賭けチップを返す
    ゲーム <-- 資金管理: クレジット
end 
UI <-- ゲーム: 勝敗結果、クレジット

@enduml