/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blackjack;

import blackjack.application.BlackJackService;
import blackjack.domain.CardPicker;
import blackjack.domain.CreditManager;
import blackjack.domain.RandomCardPicker;
import blackjack.presentation.BlackJackCUI;

/**
 * ブラックジャックのアプリケーション.
 */
public class App {
    /**
     * メインメソッド.
     * CUIの呼び出しのみ
     * @param args 引数は使用しない
     */
    public static void main(String[] args) {
        CardPicker picker = new RandomCardPicker();
        CreditManager creditManager = new CreditManager();
        BlackJackService service = new BlackJackService(creditManager, picker);
        BlackJackCUI cui = new BlackJackCUI(service);
        cui.execute();
    }
}
