/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blackjack;

import blackjack.application.BlackJackService;
import blackjack.domain.CardPicker;
import blackjack.domain.CreditManager;
import blackjack.domain.RandomCardPicker;
import blackjack.presentation.BlackJackController;
import blackjack.ui.CharacterUserInterface;

public class App {
    public static void main(String[] args) {
        CardPicker picker = new RandomCardPicker();
        CreditManager creditManager = new CreditManager();
        BlackJackService service = new BlackJackService(creditManager, picker);
        BlackJackController controller = new BlackJackController(service);
        CharacterUserInterface cui = new CharacterUserInterface(controller);
        cui.execute();
    }
}
